### ISSUE TITLE
Configuration not automatically written when creating ADS111x struct

### ISSUE THREAD

**Issue by grievouz** [wintermute101/ads111x#3]
## Description
When creating an `ADS111x` struct and passing a configuration, the configuration is not automatically written to the ADS memory. The `write_config()` method needs to be called manually after creating the struct, which is not clear from the current API design or examples.

## Current Behavior
The configuration passed to the `ADS111x::new()` method is not automatically applied to the device. Users need to manually call `write_config()` after creating the struct.

## Code Example
```rust
let config = ADS111xConfig::default()
    .mode(ads111x::Mode::Continuous)
    .pga(ads111x::ProgramableGainAmplifier::V4_096)
    .mux(ads111x::InputMultiplexer::AIN0GND)
    .dr(ads111x::DataRate::SPS8);

let mut adc = ADS111x::new(I2cDevice::new(i2c_mutex), 0x48, config)
    .expect("failed to create adc device");

// This line is necessary but not obvious:
adc.write_config(None).await.unwrap();
```

## Suggested Solutions
1. Automatically call `write_config()` within the `ADS111x::new()` method.
2. Add a separate `ADS111x::new_and_configure()` method that both creates the struct and writes the configuration.
3. (easiest) Update the documentation and examples to indicate that `write_config()` needs to be called after creating the struct.

Feel free to choose any of these solutions or suggest an alternative. I'm happy to implement the chosen solution and submit a pull request for it. Just let me know which approach you prefer!

## Thank You Note
Hi wintermute101 and all the other contributors – just wanted to say thanks for putting this library together. It's been a real lifesaver for me, especially since it's the only library I could dig up that supports async I2C.

**Comment by wintermute101** [comment]
Hey thank you for issue.
Yes you are right it is not obvious.
ad 1 - I'm not fan of doing any operation to device "behind the scenes" so this option is not proffered.
ad 2 - This is a solution and maybe right one but then, config should be an option. Then make errors to all functions when it's not set? Another solution is that "new" will create default config and "new_and_configure" let you put your own and send it (it should be stated in docs that it will start I2C operation).
I just realised that second solution will break compatibility so maybe not better.
ad 3 - In either case this should be done :) so feel free to make PR :)

Thanks async was recently provided by PR so I'm grateful for that as well.
I'm happy that is being used :)
